/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package vista;

import Controlador.CtlProducto;
import Modelo.FiltrarLista;
import Modelo.Productos;
import java.awt.BorderLayout;
import java.awt.Color;
import java.util.List;
import javax.swing.JScrollPane;
import javax.swing.ScrollPaneConstants;

/**
 *
 * @author Santiago Gaviria Oliveros Y Daniela Rojas Galvis
 */
public class Filtro extends javax.swing.JPanel {

    /**
     * Creates new form Filtro
     */
    private CtlProducto gestionProducto;
    private FiltrarLista list;

    public Filtro() {
        initComponents();
        gestionProducto = new CtlProducto();
        setLayout(new BorderLayout());
        setBackground(Color.WHITE);
        list = new FiltrarLista();
        JScrollPane pane = new JScrollPane(list, ScrollPaneConstants.VERTICAL_SCROLLBAR_ALWAYS, ScrollPaneConstants.HORIZONTAL_SCROLLBAR_NEVER);
        list.getCampoFiltro().setBounds(100, 0, 200, 160);
        list.getCampoFiltro().setVisible(true);
        pane.setBounds(100, 0, 400, 200);
        pane.setVisible(true);
        add(pane, BorderLayout.CENTER);
        add(list.getCampoFiltro(), BorderLayout.NORTH);
    }

    public void actualizar(List<Productos> productos) {
        list.borrarItem();
        String[] datos = new String[productos.size()];
        for (int i = 0; i < productos.size(); i++) {
            datos[i] = productos.get(i).getNombreproducto();
            list.agregarItem(datos[i]);
        }
        add(list.getCampoFiltro(), BorderLayout.NORTH);
    }
    
    public void vacio(){
        list.borrarItem();
        add(list.getCampoFiltro(), BorderLayout.NORTH);
    }

   
    public FiltrarLista getList() {
        return list;
    }

    public void setList(FiltrarLista list) {
        this.list = list;

    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
                layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGap(0, 400, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
                layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGap(0, 300, Short.MAX_VALUE)
        );
    }// </editor-fold>//GEN-END:initComponents

    // Variables declaration - do not modify//GEN-BEGIN:variables
    // End of variables declaration//GEN-END:variables
}
