/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package Vista;

import Controlador.CtlLogin;
import Controlador.CtlOferta;
import Controlador.CtlSubasta;
import Controlador.CtlVentana;
import Modelo.Ofertas;
import Modelo.Subastas;
import java.awt.Color;
import java.util.ArrayList;
import java.util.Date;
import java.util.List;
import javax.swing.JOptionPane;

/**
 *
 * @author ASUS
 */
public class VentanaLogin extends javax.swing.JFrame {

    /**
     * Creates new form Ventana
     */
    CtlVentana gestionVentana;
    CtlLogin gestionLogin;
    CtlSubasta gestionSubasta;
    CtlOferta gestionOferta;
    double valorOferta;
    
    public VentanaLogin() {
        initComponents();
        setLocationRelativeTo(this);
        this.getContentPane().setBackground(Color.WHITE);// Color de fondo de la ventana
        gestionVentana = new CtlVentana();
        gestionLogin = new CtlLogin();
        gestionSubasta = new CtlSubasta();
        gestionOferta = new CtlOferta();
        Date fechaActual = gestionVentana.generarFechaActual();
        List<Subastas> subastas = gestionSubasta.searchEnd(fechaActual);
        gestionVentana.cambiarEstadoSubastas(subastas);
        List<Ofertas> oferta = new ArrayList<>();
        for (int i = 0; i < subastas.size(); i++) {
            oferta = gestionOferta.listOfertaSolicitud(subastas.get(i).getCodigosubasta());
        }
        if (!oferta.isEmpty()) {
            valorOferta = gestionVentana.verificarOfertaMenor(oferta);
        }
        gestionVentana.actualizarPerdedoresOfertas(oferta,valorOferta);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel4 = new javax.swing.JLabel();
        jLabel1 = new javax.swing.JLabel();
        jTFNickname = new javax.swing.JTextField();
        jLabel2 = new javax.swing.JLabel();
        jBIngresar = new javax.swing.JButton();
        jPFContrasenia = new javax.swing.JPasswordField();
        jBRegistrar = new javax.swing.JButton();
        jLTitulo = new javax.swing.JLabel();

        jLabel4.setText("jLabel4");

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setResizable(false);

        jLabel1.setFont(new java.awt.Font("Maiandra GD", 1, 14)); // NOI18N
        jLabel1.setText("Usuario:");

        jLabel2.setFont(new java.awt.Font("Maiandra GD", 1, 14)); // NOI18N
        jLabel2.setText("Contraseña:");

        jBIngresar.setFont(new java.awt.Font("Maiandra GD", 1, 14)); // NOI18N
        jBIngresar.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Img/5.png"))); // NOI18N
        jBIngresar.setText("Ingresar");
        jBIngresar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jBIngresarActionPerformed(evt);
            }
        });

        jBRegistrar.setFont(new java.awt.Font("Maiandra GD", 1, 14)); // NOI18N
        jBRegistrar.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Img/add-user.png"))); // NOI18N
        jBRegistrar.setText("Registrate");
        jBRegistrar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jBRegistrarActionPerformed(evt);
            }
        });

        jLTitulo.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Img/img-empresa.png"))); // NOI18N

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLTitulo, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addContainerGap())
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jBIngresar)
                        .addGap(18, 18, 18)
                        .addComponent(jBRegistrar))
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel2)
                            .addComponent(jLabel1, javax.swing.GroupLayout.Alignment.TRAILING))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jTFNickname, javax.swing.GroupLayout.PREFERRED_SIZE, 182, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jPFContrasenia, javax.swing.GroupLayout.PREFERRED_SIZE, 183, javax.swing.GroupLayout.PREFERRED_SIZE))))
                .addGap(230, 230, 230))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLTitulo, javax.swing.GroupLayout.PREFERRED_SIZE, 498, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jTFNickname, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel1))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel2)
                    .addComponent(jPFContrasenia, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(jBIngresar)
                    .addComponent(jBRegistrar, javax.swing.GroupLayout.PREFERRED_SIZE, 57, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jBIngresarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jBIngresarActionPerformed
        // TODO add your handling code here:
        if (gestionVentana.verificarDatosIngreso(jTFNickname, jPFContrasenia)) {
            JOptionPane.showMessageDialog(null, "Ingrese los datos para ingresar al Sistema");
        } else {
            String nickname = jTFNickname.getText();
            char[] pass = jPFContrasenia.getPassword();
            String password = new String(pass);// gestionar el ingreso al sistema
            String tipoUsuario = gestionLogin.ingresar(nickname, password);
            switch (tipoUsuario) {
                case "Administrador":
                    JOptionPane.showMessageDialog(null, "Bienvenido Admininstrador " + nickname);
                    new VentanaAdministrador(nickname).setVisible(true);
                    limpiarCamposLogin();
                    break;
                case "Empresario":
                    JOptionPane.showMessageDialog(null, "Bienvenido Empresario " + nickname);
                    new VentanaEmpresario(nickname).setVisible(true);
                    limpiarCamposLogin();
                    break;
                
                case "Proveedor":
                    JOptionPane.showMessageDialog(null, "Bienvenido Proveedor " + nickname);
                    new VentanaProveedor(nickname, valorOferta).setVisible(true);
                    limpiarCamposLogin();
                    break;
                
                default:
                    JOptionPane.showMessageDialog(null, "El usuario no se encuentra registrado");
                    break;
            }
        }

    }//GEN-LAST:event_jBIngresarActionPerformed

    private void jBRegistrarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jBRegistrarActionPerformed
        // TODO add your handling code here:
        new VentanaRegistro().setVisible(true);
    }//GEN-LAST:event_jBRegistrarActionPerformed
    
    public void limpiarCamposLogin() {
        jTFNickname.setText(null);
        jPFContrasenia.setText(null);
    }

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(VentanaLogin.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(VentanaLogin.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(VentanaLogin.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(VentanaLogin.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new VentanaLogin().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jBIngresar;
    private javax.swing.JButton jBRegistrar;
    private javax.swing.JLabel jLTitulo;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JPasswordField jPFContrasenia;
    private javax.swing.JTextField jTFNickname;
    // End of variables declaration//GEN-END:variables
}
