/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package Vista;

import Controlador.CtlAdministrador;
import Controlador.CtlCategoria;
import Controlador.CtlEmpresario;
import Controlador.CtlOferta;
////import Controlador.CtlOferta;
import Controlador.CtlProducto;
import Controlador.CtlSubasta;
import Controlador.CtlVentana;
import Modelo.Empresarios;
import Modelo.Ofertas;
import Modelo.Productos;
import Modelo.Subastas;
import java.awt.Color;
import java.util.Date;
import java.util.List;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;

/**
 *
 * @author Santiago Gaviria Oliveros
 */
public class VentanaEmpresario extends javax.swing.JFrame {

    /**
     * Creates new form VentanaEmpresario
     */
    CtlCategoria gestionCategoria;
    CtlVentana gestionVentana;
    CtlSubasta gestionSubasta;
    CtlAdministrador gestionAdmin;
    CtlProducto gestionProducto;
    CtlEmpresario gestionEmpresario;
    CtlOferta gestionOferta;
    vista.Filtro filtro;
    String empresario;
    int codigoSolicitudOferta;
    int codigoOferta;

    public VentanaEmpresario(String empresario) {
        initComponents();
        setLocationRelativeTo(this);
        this.getContentPane().setBackground(Color.WHITE);// Color de fondo de la ventana
        gestionCategoria = new CtlCategoria();
        gestionVentana = new CtlVentana();
        gestionSubasta = new CtlSubasta();
        gestionAdmin = new CtlAdministrador();
        gestionProducto = new CtlProducto();
        gestionEmpresario = new CtlEmpresario();
        gestionOferta = new CtlOferta();
        this.empresario = empresario;
        jLNombreEmp.setText("EMPRESARI@ " + empresario.toUpperCase());
        gestionVentana.cargarCategorias(jCBCategorias);
        jTFFechaInicial.setText(gestionVentana.generarFechaActualCadena());
        filtro = new vista.Filtro();
        filtro.setBounds(100, 0, 400, 200);
        filtro.setVisible(true);
        jPProductos.add(filtro);
        jTSubasta.setModel(gestionVentana.listarSubastas(gestionEmpresario.searchNombre(empresario).getCedula()));

    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     *
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLNombreEmp = new javax.swing.JLabel();
        jTabbedPane1 = new javax.swing.JTabbedPane();
        jPanel1 = new javax.swing.JPanel();
        jLabel2 = new javax.swing.JLabel();
        jCBCategorias = new javax.swing.JComboBox();
        jPProductos = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jSCantidad = new javax.swing.JSpinner();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jDFechaFinal = new com.toedter.calendar.JDateChooser();
        jLabel5 = new javax.swing.JLabel();
        jDFechaEntrega = new com.toedter.calendar.JDateChooser();
        jScrollPane1 = new javax.swing.JScrollPane();
        jTADescripcion = new javax.swing.JTextArea();
        jLabel6 = new javax.swing.JLabel();
        jBEnviarSolicitud = new javax.swing.JButton();
        jTFFechaInicial = new javax.swing.JTextField();
        jPanel2 = new javax.swing.JPanel();
        jPanel6 = new javax.swing.JPanel();
        jScrollPane4 = new javax.swing.JScrollPane();
        jTSubasta = new javax.swing.JTable();
        jPanel3 = new javax.swing.JPanel();
        jScrollPane6 = new javax.swing.JScrollPane();
        jTOfertas = new javax.swing.JTable();
        jLabel9 = new javax.swing.JLabel();
        jScrollPane2 = new javax.swing.JScrollPane();
        jTADetallesOferta = new javax.swing.JTextArea();
        jBConsultarOfertas = new javax.swing.JButton();
        jBAceptarOferta = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);

        jLNombreEmp.setText("Empresaria");

        jPanel1.setBackground(new java.awt.Color(255, 255, 255));

        jLabel2.setText("Categoria del Producto");

        jCBCategorias.addItemListener(new java.awt.event.ItemListener() {
            public void itemStateChanged(java.awt.event.ItemEvent evt) {
                jCBCategoriasItemStateChanged(evt);
            }
        });

        jPProductos.setBackground(new java.awt.Color(255, 255, 255));

        javax.swing.GroupLayout jPProductosLayout = new javax.swing.GroupLayout(jPProductos);
        jPProductos.setLayout(jPProductosLayout);
        jPProductosLayout.setHorizontalGroup(
            jPProductosLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 537, Short.MAX_VALUE)
        );
        jPProductosLayout.setVerticalGroup(
            jPProductosLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 208, Short.MAX_VALUE)
        );

        jLabel1.setText("Cantidad:");

        jSCantidad.setModel(new javax.swing.SpinnerNumberModel(Integer.valueOf(0), Integer.valueOf(0), null, Integer.valueOf(1)));

        jLabel3.setText("Fecha Inicio:");

        jLabel4.setText("Fecha Cierre:");

        jLabel5.setText("Fecha Entrega:");

        jTADescripcion.setColumns(20);
        jTADescripcion.setRows(5);
        jScrollPane1.setViewportView(jTADescripcion);

        jLabel6.setText("Descripción");

        jBEnviarSolicitud.setText("Enviar Solicitud");
        jBEnviarSolicitud.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jBEnviarSolicitudActionPerformed(evt);
            }
        });

        jTFFechaInicial.setDisabledTextColor(new java.awt.Color(0, 0, 0));
        jTFFechaInicial.setEnabled(false);

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                .addGap(0, 0, Short.MAX_VALUE)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(250, 250, 250)
                        .addComponent(jBEnviarSolicitud))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(239, 239, 239)
                        .addComponent(jLabel1)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(jSCantidad, javax.swing.GroupLayout.PREFERRED_SIZE, 44, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 626, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(264, 264, 264)
                        .addComponent(jLabel6)))
                .addGap(136, 136, 136))
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(64, 64, 64)
                        .addComponent(jLabel3)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(jTFFechaInicial, javax.swing.GroupLayout.PREFERRED_SIZE, 172, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(jLabel4)
                        .addGap(18, 18, 18)
                        .addComponent(jDFechaFinal, javax.swing.GroupLayout.PREFERRED_SIZE, 168, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(34, 34, 34)
                        .addComponent(jLabel5)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(jDFechaEntrega, javax.swing.GroupLayout.PREFERRED_SIZE, 168, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(194, 194, 194)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jPProductos, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                                .addComponent(jLabel2)
                                .addGap(18, 18, 18)
                                .addComponent(jCBCategorias, javax.swing.GroupLayout.PREFERRED_SIZE, 252, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(82, 82, 82)))))
                .addGap(0, 70, Short.MAX_VALUE))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(30, 30, 30)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel2)
                    .addComponent(jCBCategorias, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addComponent(jPProductos, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jDFechaFinal, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel4)
                    .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(jLabel3)
                        .addComponent(jTFFechaInicial, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addComponent(jDFechaEntrega, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel5))
                .addGap(18, 18, 18)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel1)
                    .addComponent(jSCantidad, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jLabel6)
                .addGap(1, 1, 1)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 96, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jBEnviarSolicitud)
                .addContainerGap(40, Short.MAX_VALUE))
        );

        jTabbedPane1.addTab("Subasta", jPanel1);

        jPanel2.setBackground(new java.awt.Color(255, 255, 255));

        jPanel6.setBackground(new java.awt.Color(255, 255, 255));
        jPanel6.setBorder(javax.swing.BorderFactory.createTitledBorder(null, "Subastas", javax.swing.border.TitledBorder.CENTER, javax.swing.border.TitledBorder.DEFAULT_POSITION, new java.awt.Font("Century Gothic", 1, 14))); // NOI18N

        jTSubasta.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null}
            },
            new String [] {
                "Codigo Subasta", "Cantidad", "Estado", "Fecha Inicio", "Fecha Final", "Fecha Entrega", "Producto"
            }
        ));
        jTSubasta.setGridColor(new java.awt.Color(255, 255, 255));
        jTSubasta.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jTSubastaMouseClicked(evt);
            }
        });
        jScrollPane4.setViewportView(jTSubasta);

        javax.swing.GroupLayout jPanel6Layout = new javax.swing.GroupLayout(jPanel6);
        jPanel6.setLayout(jPanel6Layout);
        jPanel6Layout.setHorizontalGroup(
            jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jScrollPane4)
        );
        jPanel6Layout.setVerticalGroup(
            jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel6Layout.createSequentialGroup()
                .addComponent(jScrollPane4, javax.swing.GroupLayout.PREFERRED_SIZE, 127, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(26, Short.MAX_VALUE))
        );

        jPanel3.setBackground(new java.awt.Color(255, 255, 255));
        jPanel3.setBorder(javax.swing.BorderFactory.createTitledBorder(null, "Ofertas", javax.swing.border.TitledBorder.CENTER, javax.swing.border.TitledBorder.DEFAULT_POSITION, new java.awt.Font("Century Gothic", 1, 14), new java.awt.Color(0, 0, 0))); // NOI18N

        jTOfertas.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null, null},
                {null, null, null, null, null},
                {null, null, null, null, null},
                {null, null, null, null, null}
            },
            new String [] {
                "Codigo", "Valor", "Proveedor", "Fecha Oferta", "Codigo Subasta"
            }
        ));
        jTOfertas.setGridColor(new java.awt.Color(255, 255, 255));
        jTOfertas.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jTOfertasMouseClicked(evt);
            }
        });
        jScrollPane6.setViewportView(jTOfertas);

        jLabel9.setFont(new java.awt.Font("Century Gothic", 1, 14)); // NOI18N
        jLabel9.setText("Detalles Oferta:");

        jTADetallesOferta.setEditable(false);
        jTADetallesOferta.setColumns(20);
        jTADetallesOferta.setRows(5);
        jTADetallesOferta.setDisabledTextColor(new java.awt.Color(0, 0, 0));
        jTADetallesOferta.setEnabled(false);
        jScrollPane2.setViewportView(jTADetallesOferta);

        javax.swing.GroupLayout jPanel3Layout = new javax.swing.GroupLayout(jPanel3);
        jPanel3.setLayout(jPanel3Layout);
        jPanel3Layout.setHorizontalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jScrollPane6, javax.swing.GroupLayout.DEFAULT_SIZE, 900, Short.MAX_VALUE)
                .addContainerGap())
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel3Layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jLabel9)
                .addGap(27, 27, 27)
                .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 399, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(190, 190, 190))
        );
        jPanel3Layout.setVerticalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addComponent(jScrollPane6, javax.swing.GroupLayout.PREFERRED_SIZE, 110, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel3Layout.createSequentialGroup()
                        .addGap(11, 11, 11)
                        .addComponent(jLabel9))
                    .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 52, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        jBConsultarOfertas.setFont(new java.awt.Font("Century Gothic", 1, 12)); // NOI18N
        jBConsultarOfertas.setText("Consultar");
        jBConsultarOfertas.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jBConsultarOfertasActionPerformed(evt);
            }
        });

        jBAceptarOferta.setText("Aceptar Oferta");
        jBAceptarOferta.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jBAceptarOfertaActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel6, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addComponent(jPanel3, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel2Layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jBAceptarOferta)
                .addGap(403, 403, 403))
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addGap(413, 413, 413)
                .addComponent(jBConsultarOfertas)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jPanel6, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(jBConsultarOfertas)
                .addGap(18, 18, 18)
                .addComponent(jPanel3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jBAceptarOferta)
                .addContainerGap(42, Short.MAX_VALUE))
        );

        jTabbedPane1.addTab("Solicitudes", jPanel2);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jTabbedPane1)
                .addContainerGap())
            .addGroup(layout.createSequentialGroup()
                .addGap(437, 437, 437)
                .addComponent(jLNombreEmp)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLNombreEmp)
                .addGap(18, 18, 18)
                .addComponent(jTabbedPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 576, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jCBCategoriasItemStateChanged(java.awt.event.ItemEvent evt) {//GEN-FIRST:event_jCBCategoriasItemStateChanged
        // TODO add your handling code here:
        try {
            List<Productos> productos = gestionProducto.listProductosCate((String) jCBCategorias.getSelectedItem());
            if (productos.isEmpty()) {
                filtro.vacio();
            } else {
                filtro.actualizar(productos);
            }
        } catch (NumberFormatException | NullPointerException e) {
        }

    }//GEN-LAST:event_jCBCategoriasItemStateChanged

    private void jBEnviarSolicitudActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jBEnviarSolicitudActionPerformed
        // TODO add your handling code here:
        if (gestionVentana.verificarDatosEnvioSolicitd(filtro.getList(), jDFechaEntrega, jDFechaFinal,
                jSCantidad, jTADescripcion)) {
            JOptionPane.showMessageDialog(null, "Digita todos los campos para enviar la Subasta");
        } else {
            String nombreProducto = (String) filtro.getList().getSelectedValue();
            int cantidad = Integer.parseInt(jSCantidad.getValue() + "");
            Date fechaEntrega = jDFechaEntrega.getDate();
            Date fechaInicio = gestionVentana.generarFechaActual();
            Date fechaFinal = jDFechaFinal.getDate();
            String descripcion = jTADescripcion.getText();
            Empresarios empre = gestionEmpresario.searchNombre(empresario);
            System.out.println(empresario);
            System.out.println(empre.getCedula());
            Productos pro = gestionProducto.searchNombre(nombreProducto);
            if (fechaInicio.compareTo(fechaFinal) == 0) {
                JOptionPane.showMessageDialog(null, "La Fecha de Cierre deber ser diferente a la Fecha Inicial");
            } else if (fechaInicio.compareTo(fechaFinal) == 1) {
                JOptionPane.showMessageDialog(null, "La Fecha de Cierre deber ser mayor a la Fecha Inicial");
            } else if (fechaFinal.compareTo(fechaEntrega) == 1) {
                JOptionPane.showMessageDialog(null, "La Fecha de Entrega deber ser mayor a la Fecha de Cierre");
            } else {
                if (gestionSubasta.save(cantidad, true, fechaInicio, fechaFinal, fechaEntrega, descripcion, empre.getCedula(),
                        pro.getCodigo())) {
                    JOptionPane.showMessageDialog(null, "La Subasta ha sido creada");
                    limpiarCamposEnvioSolicitud();
                    jTSubasta.setModel(gestionVentana.listarSubastas(gestionEmpresario.searchNombre(empresario).getCedula()));
                }
            }
        }
    }//GEN-LAST:event_jBEnviarSolicitudActionPerformed

    private void jBConsultarOfertasActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jBConsultarOfertasActionPerformed
        // TODO add your handling code here:
        if (gestionVentana.validarSeleccionSolicitud(jTSubasta)) {
            if (!gestionOferta.listOfertaSolicitud(codigoSolicitudOferta).isEmpty()) {
                JOptionPane.showMessageDialog(null, "Ofertas Encontradas");
                jTOfertas.setModel(gestionVentana.listarOfertasSubasta(gestionOferta.listOfertaSolicitud(codigoSolicitudOferta)));
            } else {
                JOptionPane.showMessageDialog(null, "No hay Ofertas asociadas a la solicitud seleccionada");
                jTADetallesOferta.setText(null);
                DefaultTableModel vacio = new DefaultTableModel();
                jTOfertas.setModel(gestionVentana.listarOfertasSubasta(gestionOferta.listOfertaSolicitud(codigoSolicitudOferta)));
            }
        } else {
            JOptionPane.showMessageDialog(null, "Seleccione una Solicitud para consultar las Ofertas");
        }
    }//GEN-LAST:event_jBConsultarOfertasActionPerformed

    private void jTSubastaMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jTSubastaMouseClicked
        // TODO add your handling code here:
        int posSolicitud = jTSubasta.getSelectedRow();
        codigoSolicitudOferta = Integer.parseInt(jTSubasta.getValueAt(posSolicitud, 0) + "");
    }//GEN-LAST:event_jTSubastaMouseClicked

    private void jTOfertasMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jTOfertasMouseClicked
        // TODO add your handling code here:
        int posSolicitudoferta = jTOfertas.getSelectedRow();
        codigoOferta = Integer.parseInt(jTOfertas.getValueAt(posSolicitudoferta, 0) + "");
        Ofertas ofe = gestionOferta.searchOferta(codigoOferta);
        jTADetallesOferta.setText(ofe.getDetallesoferta());
    }//GEN-LAST:event_jTOfertasMouseClicked

    private void jBAceptarOfertaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jBAceptarOfertaActionPerformed
        // TODO add your handling code here
        if (gestionVentana.validarSeleccionOferta(jTOfertas)) {
            int opc = JOptionPane.showConfirmDialog(null, "Desea Aceptar la Oferta Seleccionada", "Ganador según su Criterio", 0);
            if (opc == 0) {
                Ofertas ofe = gestionOferta.searchOferta(codigoOferta);
                Subastas sub = ofe.getSubastasCodigosubasta();
                if (gestionSubasta.update(sub.getCodigosubasta(), sub.getCantidadproductos(), false, sub.getFechainicio(),
                        sub.getFechafinal(), sub.getFechaentrega(), sub.getDescripcion(),
                        sub.getEmpresariosCedula().getCedula(), sub.getProductosCodigo().getCodigo())) {
                    JOptionPane.showMessageDialog(null, "La Subasta de codigo " + sub.getCodigosubasta()
                            + " del producto " + sub.getProductosCodigo().getNombreproducto() + " se ha "
                            + " cerrado correctamente", "Ganador Proveedor " + ofe.getProveedoresCedula().getNombrecompleto()
                            + " de la Entidad " + ofe.getProveedoresCedula().getNombreentidad(), JOptionPane.INFORMATION_MESSAGE);
                    jTSubasta.setModel(gestionVentana.listarSubastas(gestionEmpresario.searchNombre(empresario).getCedula()));
                    
                    DefaultTableModel vacio = new DefaultTableModel();
                    jTOfertas.setModel(vacio);
                    jTADetallesOferta.setText(null);
                } else {
                    JOptionPane.showMessageDialog(null, "error");
                }
            }
        } else {
            JOptionPane.showMessageDialog(null, "Seleccione una Oferta para aceptar a su solicitud");
        }
    }//GEN-LAST:event_jBAceptarOfertaActionPerformed

    /**
     * Limpia los campos de envio de una solicitud
     */
    public void limpiarCamposEnvioSolicitud() {
        jCBCategorias.setSelectedIndex(0);
        filtro.vacio();
        jDFechaEntrega.setDate(null);
        jDFechaFinal.setDate(null);
        jSCantidad.setValue(0);
        jTADescripcion.setText(null);
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jBAceptarOferta;
    private javax.swing.JButton jBConsultarOfertas;
    private javax.swing.JButton jBEnviarSolicitud;
    private javax.swing.JComboBox jCBCategorias;
    private com.toedter.calendar.JDateChooser jDFechaEntrega;
    private com.toedter.calendar.JDateChooser jDFechaFinal;
    private javax.swing.JLabel jLNombreEmp;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JPanel jPProductos;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JPanel jPanel6;
    private javax.swing.JSpinner jSCantidad;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JScrollPane jScrollPane4;
    private javax.swing.JScrollPane jScrollPane6;
    private javax.swing.JTextArea jTADescripcion;
    private javax.swing.JTextArea jTADetallesOferta;
    private javax.swing.JTextField jTFFechaInicial;
    private javax.swing.JTable jTOfertas;
    private javax.swing.JTable jTSubasta;
    private javax.swing.JTabbedPane jTabbedPane1;
    // End of variables declaration//GEN-END:variables
}
