/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package Vista;

import Controlador.CtlAdministrador;
import Controlador.CtlCategoria;
import Controlador.CtlProducto;
import Controlador.CtlVentana;
import Modelo.Administradores;
import Modelo.Categorias;
import Modelo.Productos;
import java.awt.Color;
import java.util.List;
import javax.swing.JOptionPane;

/**
 *
 * @author Santiago Gaviria Oliveros
 */
public class VentanaAdministrador extends javax.swing.JFrame {

    /**
     * Creates new form VentanaAdministrador
     */
    CtlVentana gestionVentana;
    CtlCategoria gestionCategoria;
    CtlProducto gestionProducto;
    CtlAdministrador gestionAdministrador;
    String nombreAdmin;
    int codigoCategoria = -1;
    int codigoProducto = -1;

    public VentanaAdministrador(String nombre) {
        initComponents();
        setLocationRelativeTo(this);
        this.getContentPane().setBackground(Color.WHITE);// Color de fondo de la ventana
        gestionVentana = new CtlVentana();
        gestionCategoria = new CtlCategoria();
        gestionVentana.cargarCategorias(jCBCategorias);
        gestionProducto = new CtlProducto();
        gestionAdministrador = new CtlAdministrador();
        this.nombreAdmin = nombre;
        jTCategorias.setModel(gestionVentana.listarCategorias());
        jTProductos.setModel(gestionVentana.listarProductos());
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jTabbedPane1 = new javax.swing.JTabbedPane();
        jPanel3 = new javax.swing.JPanel();
        jTabbedPane2 = new javax.swing.JTabbedPane();
        jTabbedPane3 = new javax.swing.JTabbedPane();
        jPanel5 = new javax.swing.JPanel();
        jLabel2 = new javax.swing.JLabel();
        jTFNombreCategoria = new javax.swing.JTextField();
        jBRegistrarCategoria = new javax.swing.JButton();
        jScrollPane1 = new javax.swing.JScrollPane();
        jTFDescripcionCategoria = new javax.swing.JTextArea();
        jLabel3 = new javax.swing.JLabel();
        jBBuscarCategoria = new javax.swing.JButton();
        jBEditarCategoria = new javax.swing.JButton();
        jBEliminarCategoria = new javax.swing.JButton();
        jScrollPane2 = new javax.swing.JScrollPane();
        jTCategorias = new javax.swing.JTable();
        jButton1 = new javax.swing.JButton();
        jPanel1 = new javax.swing.JPanel();
        jLabel4 = new javax.swing.JLabel();
        jTFNombreProducto = new javax.swing.JTextField();
        jLabel6 = new javax.swing.JLabel();
        jCBCategorias = new javax.swing.JComboBox();
        jLabel5 = new javax.swing.JLabel();
        jScrollPane3 = new javax.swing.JScrollPane();
        jTADescripcionProducto = new javax.swing.JTextArea();
        jScrollPane4 = new javax.swing.JScrollPane();
        jTFDescripcionCate = new javax.swing.JTextArea();
        jLabel7 = new javax.swing.JLabel();
        jBRegistrarProducto = new javax.swing.JButton();
        jBBuscarProducto = new javax.swing.JButton();
        jBEditarProducto = new javax.swing.JButton();
        jBEliminarProducto = new javax.swing.JButton();
        jScrollPane5 = new javax.swing.JScrollPane();
        jTProductos = new javax.swing.JTable();
        jBLimpiarCamposGestionProductos = new javax.swing.JButton();
        jLabel8 = new javax.swing.JLabel();

        javax.swing.GroupLayout jPanel3Layout = new javax.swing.GroupLayout(jPanel3);
        jPanel3.setLayout(jPanel3Layout);
        jPanel3Layout.setHorizontalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 100, Short.MAX_VALUE)
        );
        jPanel3Layout.setVerticalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 100, Short.MAX_VALUE)
        );

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        setResizable(false);

        jTabbedPane3.setBackground(new java.awt.Color(255, 255, 255));
        jTabbedPane3.setFont(new java.awt.Font("Maiandra GD", 1, 14)); // NOI18N

        jPanel5.setBackground(new java.awt.Color(255, 255, 255));

        jLabel2.setFont(new java.awt.Font("Maiandra GD", 1, 12)); // NOI18N
        jLabel2.setText("Nombre:");

        jTFNombreCategoria.setFont(new java.awt.Font("Maiandra GD", 0, 12)); // NOI18N

        jBRegistrarCategoria.setFont(new java.awt.Font("Maiandra GD", 1, 12)); // NOI18N
        jBRegistrarCategoria.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Img/save.png"))); // NOI18N
        jBRegistrarCategoria.setText("Registrar");
        jBRegistrarCategoria.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jBRegistrarCategoriaActionPerformed(evt);
            }
        });

        jTFDescripcionCategoria.setColumns(20);
        jTFDescripcionCategoria.setFont(new java.awt.Font("Maiandra GD", 0, 12)); // NOI18N
        jTFDescripcionCategoria.setRows(5);
        jScrollPane1.setViewportView(jTFDescripcionCategoria);

        jLabel3.setFont(new java.awt.Font("Maiandra GD", 1, 12)); // NOI18N
        jLabel3.setText("Descripción");

        jBBuscarCategoria.setFont(new java.awt.Font("Maiandra GD", 1, 12)); // NOI18N
        jBBuscarCategoria.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Img/search.png"))); // NOI18N
        jBBuscarCategoria.setText("Buscar");
        jBBuscarCategoria.setPreferredSize(new java.awt.Dimension(77, 23));
        jBBuscarCategoria.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jBBuscarCategoriaActionPerformed(evt);
            }
        });

        jBEditarCategoria.setFont(new java.awt.Font("Maiandra GD", 1, 12)); // NOI18N
        jBEditarCategoria.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Img/edit-notes.png"))); // NOI18N
        jBEditarCategoria.setText("Editar");
        jBEditarCategoria.setPreferredSize(new java.awt.Dimension(77, 23));
        jBEditarCategoria.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jBEditarCategoriaActionPerformed(evt);
            }
        });

        jBEliminarCategoria.setFont(new java.awt.Font("Maiandra GD", 1, 12)); // NOI18N
        jBEliminarCategoria.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Img/delete.png"))); // NOI18N
        jBEliminarCategoria.setText("Eliminar");
        jBEliminarCategoria.setPreferredSize(new java.awt.Dimension(77, 23));
        jBEliminarCategoria.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jBEliminarCategoriaActionPerformed(evt);
            }
        });

        jTCategorias.setFont(new java.awt.Font("Maiandra GD", 1, 12)); // NOI18N
        jTCategorias.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null},
                {null, null, null},
                {null, null, null},
                {null, null, null},
                {null, null, null},
                {null, null, null},
                {null, null, null}
            },
            new String [] {
                "Codigo", "Nombre", "Descripcion"
            }
        ));
        jScrollPane2.setViewportView(jTCategorias);

        jButton1.setFont(new java.awt.Font("Maiandra GD", 1, 12)); // NOI18N
        jButton1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Img/setting.png"))); // NOI18N
        jButton1.setText("Limpiar Campos");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel5Layout = new javax.swing.GroupLayout(jPanel5);
        jPanel5.setLayout(jPanel5Layout);
        jPanel5Layout.setHorizontalGroup(
            jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel5Layout.createSequentialGroup()
                .addGroup(jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel5Layout.createSequentialGroup()
                        .addGroup(jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanel5Layout.createSequentialGroup()
                                .addGap(84, 84, 84)
                                .addGroup(jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.CENTER)
                                    .addGroup(javax.swing.GroupLayout.Alignment.LEADING, jPanel5Layout.createSequentialGroup()
                                        .addGap(226, 226, 226)
                                        .addComponent(jLabel2)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                        .addComponent(jTFNombreCategoria, javax.swing.GroupLayout.PREFERRED_SIZE, 253, javax.swing.GroupLayout.PREFERRED_SIZE))
                                    .addGroup(javax.swing.GroupLayout.Alignment.LEADING, jPanel5Layout.createSequentialGroup()
                                        .addGap(362, 362, 362)
                                        .addComponent(jLabel3))))
                            .addGroup(jPanel5Layout.createSequentialGroup()
                                .addGap(130, 130, 130)
                                .addGroup(jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addGroup(jPanel5Layout.createSequentialGroup()
                                        .addComponent(jBRegistrarCategoria, javax.swing.GroupLayout.PREFERRED_SIZE, 134, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                        .addComponent(jBBuscarCategoria, javax.swing.GroupLayout.PREFERRED_SIZE, 124, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                        .addComponent(jBEditarCategoria, javax.swing.GroupLayout.PREFERRED_SIZE, 130, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                        .addComponent(jBEliminarCategoria, javax.swing.GroupLayout.PREFERRED_SIZE, 123, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                        .addComponent(jButton1))
                                    .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 702, javax.swing.GroupLayout.PREFERRED_SIZE))))
                        .addGap(0, 93, Short.MAX_VALUE))
                    .addGroup(jPanel5Layout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(jScrollPane2)))
                .addContainerGap())
        );
        jPanel5Layout.setVerticalGroup(
            jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel5Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel2)
                    .addComponent(jTFNombreCategoria, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jLabel3)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jBBuscarCategoria, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jBEditarCategoria, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jBEliminarCategoria, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jButton1, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 0, Short.MAX_VALUE)
                    .addComponent(jBRegistrarCategoria))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 117, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(23, 23, 23))
        );

        jTabbedPane3.addTab("Gestion Categorias", jPanel5);

        jPanel1.setBackground(new java.awt.Color(255, 255, 255));

        jLabel4.setFont(new java.awt.Font("Maiandra GD", 1, 12)); // NOI18N
        jLabel4.setText("Nombre Producto:");

        jTFNombreProducto.setFont(new java.awt.Font("Maiandra GD", 1, 12)); // NOI18N

        jLabel6.setFont(new java.awt.Font("Maiandra GD", 1, 12)); // NOI18N
        jLabel6.setText("Seleccione la Categoria:");

        jCBCategorias.setFont(new java.awt.Font("Maiandra GD", 1, 12)); // NOI18N
        jCBCategorias.addItemListener(new java.awt.event.ItemListener() {
            public void itemStateChanged(java.awt.event.ItemEvent evt) {
                jCBCategoriasItemStateChanged(evt);
            }
        });

        jLabel5.setFont(new java.awt.Font("Maiandra GD", 1, 12)); // NOI18N
        jLabel5.setText("Descripción:");

        jTADescripcionProducto.setColumns(20);
        jTADescripcionProducto.setFont(new java.awt.Font("Maiandra GD", 1, 12)); // NOI18N
        jTADescripcionProducto.setRows(5);
        jScrollPane3.setViewportView(jTADescripcionProducto);

        jTFDescripcionCate.setColumns(20);
        jTFDescripcionCate.setFont(new java.awt.Font("Maiandra GD", 1, 12)); // NOI18N
        jTFDescripcionCate.setRows(5);
        jTFDescripcionCate.setDisabledTextColor(new java.awt.Color(0, 0, 0));
        jTFDescripcionCate.setEnabled(false);
        jScrollPane4.setViewportView(jTFDescripcionCate);

        jLabel7.setFont(new java.awt.Font("Maiandra GD", 1, 12)); // NOI18N
        jLabel7.setText("Descripción Categoria");

        jBRegistrarProducto.setFont(new java.awt.Font("Maiandra GD", 1, 12)); // NOI18N
        jBRegistrarProducto.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Img/add-product-32.png"))); // NOI18N
        jBRegistrarProducto.setText("Registrar");
        jBRegistrarProducto.setToolTipText("");
        jBRegistrarProducto.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jBRegistrarProductoActionPerformed(evt);
            }
        });

        jBBuscarProducto.setFont(new java.awt.Font("Maiandra GD", 1, 12)); // NOI18N
        jBBuscarProducto.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Img/search-product-32.png"))); // NOI18N
        jBBuscarProducto.setText("Buscar");
        jBBuscarProducto.setPreferredSize(new java.awt.Dimension(77, 23));
        jBBuscarProducto.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jBBuscarProductoActionPerformed(evt);
            }
        });

        jBEditarProducto.setFont(new java.awt.Font("Maiandra GD", 1, 12)); // NOI18N
        jBEditarProducto.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Img/edit-product-32.png"))); // NOI18N
        jBEditarProducto.setText("Editar");
        jBEditarProducto.setPreferredSize(new java.awt.Dimension(77, 23));
        jBEditarProducto.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jBEditarProductoActionPerformed(evt);
            }
        });

        jBEliminarProducto.setFont(new java.awt.Font("Maiandra GD", 1, 12)); // NOI18N
        jBEliminarProducto.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Img/reject-product-32.png"))); // NOI18N
        jBEliminarProducto.setText("Eliminar");
        jBEliminarProducto.setPreferredSize(new java.awt.Dimension(77, 23));
        jBEliminarProducto.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jBEliminarProductoActionPerformed(evt);
            }
        });

        jTProductos.setFont(new java.awt.Font("Maiandra GD", 1, 12)); // NOI18N
        jTProductos.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Codigo", "Nombre", "Descripcion", "Categoria"
            }
        ));
        jScrollPane5.setViewportView(jTProductos);

        jBLimpiarCamposGestionProductos.setFont(new java.awt.Font("Maiandra GD", 1, 12)); // NOI18N
        jBLimpiarCamposGestionProductos.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Img/product-settings-options-32.png"))); // NOI18N
        jBLimpiarCamposGestionProductos.setText("Limpiar Campos");
        jBLimpiarCamposGestionProductos.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jBLimpiarCamposGestionProductosActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jScrollPane5)
                .addContainerGap())
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jLabel6)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jCBCategorias, javax.swing.GroupLayout.PREFERRED_SIZE, 217, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(77, 77, 77))
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(86, 86, 86)
                        .addComponent(jBRegistrarProducto)
                        .addGap(18, 18, 18)
                        .addComponent(jBBuscarProducto, javax.swing.GroupLayout.PREFERRED_SIZE, 117, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(jBEditarProducto, javax.swing.GroupLayout.PREFERRED_SIZE, 115, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(jBEliminarProducto, javax.swing.GroupLayout.PREFERRED_SIZE, 123, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(jBLimpiarCamposGestionProductos))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(72, 72, 72)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addComponent(jLabel4)
                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addGroup(jPanel1Layout.createSequentialGroup()
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                        .addComponent(jLabel5))
                                    .addGroup(jPanel1Layout.createSequentialGroup()
                                        .addGap(6, 6, 6)
                                        .addComponent(jTFNombreProducto, javax.swing.GroupLayout.PREFERRED_SIZE, 218, javax.swing.GroupLayout.PREFERRED_SIZE))))
                            .addComponent(jScrollPane3, javax.swing.GroupLayout.PREFERRED_SIZE, 340, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addGap(77, 77, 77)
                                .addComponent(jScrollPane4, javax.swing.GroupLayout.PREFERRED_SIZE, 369, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(jLabel7)
                                .addGap(108, 108, 108)))))
                .addContainerGap(77, Short.MAX_VALUE))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(jTFNombreProducto, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(jLabel6)
                        .addComponent(jCBCategorias, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addComponent(jLabel4, javax.swing.GroupLayout.Alignment.TRAILING))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel7, javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(jLabel5))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(jScrollPane3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jScrollPane4, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jBBuscarProducto, javax.swing.GroupLayout.PREFERRED_SIZE, 32, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jBEditarProducto, javax.swing.GroupLayout.PREFERRED_SIZE, 32, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jBEliminarProducto, javax.swing.GroupLayout.PREFERRED_SIZE, 32, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jBLimpiarCamposGestionProductos, javax.swing.GroupLayout.PREFERRED_SIZE, 32, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jBRegistrarProducto, javax.swing.GroupLayout.PREFERRED_SIZE, 32, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jScrollPane5, javax.swing.GroupLayout.PREFERRED_SIZE, 107, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        jTabbedPane3.addTab("Gestion Productos", jPanel1);

        jLabel8.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Img/banner_tecno.jpg"))); // NOI18N

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jTabbedPane3, javax.swing.GroupLayout.Alignment.TRAILING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jLabel8)
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel8)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jTabbedPane3, javax.swing.GroupLayout.PREFERRED_SIZE, 354, javax.swing.GroupLayout.PREFERRED_SIZE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jBRegistrarCategoriaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jBRegistrarCategoriaActionPerformed
        // TODO add your handling code here:
        if (gestionVentana.verificarDatosRegistroCategoria(jTFNombreCategoria, jTFDescripcionCategoria)) {
            JOptionPane.showMessageDialog(null, "Digite todos los campos para el registro");
        } else {
            String nombre = jTFNombreCategoria.getText();
            String descripcion = jTFDescripcionCategoria.getText();
            if (gestionCategoria.save(nombre, descripcion)) {
                JOptionPane.showMessageDialog(null, "La Categoria ha quedado registrado");
                limpiarCamposRegistroCategoria();
                gestionVentana.cargarCategorias(jCBCategorias);
                jTCategorias.setModel(gestionVentana.listarCategorias());
            } else {
                JOptionPane.showMessageDialog(null, "La Categoria ya se encuentra registrada");
            }
        }
    }//GEN-LAST:event_jBRegistrarCategoriaActionPerformed

    private void jBRegistrarProductoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jBRegistrarProductoActionPerformed
        // TODO add your handling code here:
        if (gestionVentana.verificarDatosRegistroProducto(jTFNombreProducto, jCBCategorias, jTADescripcionProducto)) {
            JOptionPane.showMessageDialog(null, "Digite todo los campos para el registro");
        } else {
            String nombreProducto = jTFNombreProducto.getText();
            String descripcionProducto = jTADescripcionProducto.getText();
            String cate = (String) jCBCategorias.getSelectedItem();
            Categorias categoria = gestionCategoria.searchNombre(cate);
            Administradores admin = gestionAdministrador.searchNombre(nombreAdmin);
            if (gestionProducto.save(nombreProducto, descripcionProducto, admin.getCedula(), categoria.getCodigo())) {
                JOptionPane.showMessageDialog(null, "El Producto ha quedado registrado");
                limpiarCamposRegistroProducto();
                jTProductos.setModel(gestionVentana.listarProductos());
            } else {
                JOptionPane.showMessageDialog(null, "El Producto ya se encuentra registrado");
            }
        }
    }//GEN-LAST:event_jBRegistrarProductoActionPerformed

    private void jCBCategoriasItemStateChanged(java.awt.event.ItemEvent evt) {//GEN-FIRST:event_jCBCategoriasItemStateChanged
        // TODO add your handling code here:
        try {
            if (jCBCategorias.getSelectedIndex() == 0) {
                jTFDescripcionCate.setText(null);
            } else {
                String cate = (String) jCBCategorias.getSelectedItem();
                Categorias categ = gestionCategoria.BuscarDes(cate);
                jTFDescripcionCate.setText(categ.getDescripcion());
            }
        } catch (NumberFormatException | NullPointerException e) {
            gestionCategoria = new CtlCategoria();
        }
    }//GEN-LAST:event_jCBCategoriasItemStateChanged

    private void jBEditarCategoriaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jBEditarCategoriaActionPerformed
        // TODO add your handling code here:
        if (codigoCategoria == -1) {
            JOptionPane.showMessageDialog(null, "Busque la Categoria a Editar");
        } else {
            String nombreCategoria = jTFNombreCategoria.getText();
            String descripcionCategoria = jTFDescripcionCategoria.getText();
            if (gestionCategoria.update(codigoCategoria, nombreCategoria, descripcionCategoria)) {
                JOptionPane.showMessageDialog(null, "La Categoria ha sido modificada");
                gestionVentana.cargarCategorias(jCBCategorias);
                jTCategorias.setModel(gestionVentana.listarCategorias());
                codigoCategoria = -1;
                limpiarCamposRegistroCategoria();
            } else {
                JOptionPane.showMessageDialog(null, "Ocurrio un error al modificar la categoria");

            }
        }
    }//GEN-LAST:event_jBEditarCategoriaActionPerformed

    private void jBEliminarCategoriaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jBEliminarCategoriaActionPerformed
        // TODO add your handling code here:
        boolean estado = true;
        try {
            int codigo = Integer.parseInt((String) JOptionPane.showInputDialog("Digite el codigo de la Categoria"));
            if (gestionProducto.searchCate(codigo) != null) {
                estado = false;
                int res = JOptionPane.showConfirmDialog(null, "La Categoria tiene asociado un producto, Desea Eliminarlo?", "Eliminacion Categoria", 0);
                System.out.println(res);
                if (res == 0) {
                    if (gestionCategoria.delete(codigo)) {
                        System.out.println("entro");
                        JOptionPane.showMessageDialog(null, "La Categoria se ha elimiando correctamente");
                        gestionVentana.cargarCategorias(jCBCategorias);
                        jTCategorias.setModel(gestionVentana.listarCategorias());
                        jTProductos.setModel(gestionVentana.listarProductos());
                    } else {
                        JOptionPane.showMessageDialog(null, "La Categoria a eliminar no se encuentra registrada");
                    }
                } else {

                }
            }
            if (estado) {
                if (gestionCategoria.delete(codigo)) {
                    System.out.println("entro1");
                    JOptionPane.showMessageDialog(null, "La Categoria se ha elimiando correctamente");
                    gestionVentana.cargarCategorias(jCBCategorias);
                    jTCategorias.setModel(gestionVentana.listarCategorias());
                    jTProductos.setModel(gestionVentana.listarProductos());

                } else {
                    JOptionPane.showMessageDialog(null, "La Categoria a eliminar no se encuentra registrada");
                }
            }
        } catch (NumberFormatException e) {

        }
    }//GEN-LAST:event_jBEliminarCategoriaActionPerformed

    private void jBBuscarProductoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jBBuscarProductoActionPerformed
        // TODO add your handling code here:
        try {
            int codigo = Integer.parseInt((String) JOptionPane.showInputDialog("Digite el codigo de el Producto"));
            Productos producto = gestionProducto.search(codigo);
            if (producto != null) {
                JOptionPane.showMessageDialog(null, "Producto Encontrado");
                jTFNombreProducto.setText(producto.getNombreproducto());
                jCBCategorias.setSelectedItem(producto.getCategoriasCodigo().getNombre());
                jTADescripcionProducto.setText(producto.getDescripcion());
                codigoProducto = producto.getCodigo();
            } else {
                JOptionPane.showMessageDialog(null, "El producto no se encuentra registrado");
            }
        } catch (NumberFormatException e) {

        }
    }//GEN-LAST:event_jBBuscarProductoActionPerformed

    private void jBEditarProductoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jBEditarProductoActionPerformed
        // TODO add your handling code here:
        if (codigoProducto == -1) {
            JOptionPane.showMessageDialog(null, "Busque el Producto a Editar");
        } else {
            String nombreProducto = jTFNombreProducto.getText();
            String descripcionProducto = jTADescripcionProducto.getText();
            String cate = (String) jCBCategorias.getSelectedItem();
            Categorias categoria = gestionCategoria.searchNombre(cate);
            Administradores admin = gestionAdministrador.searchNombre(nombreAdmin);
            if (gestionProducto.update(codigoProducto, nombreProducto, descripcionProducto, admin.getCedula(), categoria.getCodigo())) {
                JOptionPane.showMessageDialog(null, "El Producto se ha modificado");
                jTProductos.setModel(gestionVentana.listarProductos());
                limpiarCamposRegistroProducto();
                codigoProducto = -1;
            } else {
                JOptionPane.showMessageDialog(null, "Ocurrio un error al modificar el producto");

            }
        }
    }//GEN-LAST:event_jBEditarProductoActionPerformed

    private void jBEliminarProductoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jBEliminarProductoActionPerformed
        // TODO add your handling code here:
        try {
            int codigo = Integer.parseInt((String) JOptionPane.showInputDialog("Digite el producto de el Producto"));
            if (gestionProducto.delete(codigo)) {
                JOptionPane.showMessageDialog(null, "El Producto se ha elimiando correctamente");
                jTProductos.setModel(gestionVentana.listarProductos());
            } else {
                JOptionPane.showMessageDialog(null, "La Categoria a eliminar no se encuentra registrada");
            }
        } catch (NumberFormatException e) {

        }
    }//GEN-LAST:event_jBEliminarProductoActionPerformed

    private void jBBuscarCategoriaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jBBuscarCategoriaActionPerformed
        // TODO add your handling code here:
        try {
            int codigo = Integer.parseInt((String) JOptionPane.showInputDialog("Digite el codigo de la Categoria"));
            Categorias cate = gestionCategoria.search(codigo);
            if (cate != null) {
                JOptionPane.showMessageDialog(null, "Categoria Encontrada");
                jTFNombreCategoria.setText(cate.getNombre());
                jTFDescripcionCategoria.setText(cate.getDescripcion());
                codigoCategoria = cate.getCodigo();
            } else {
                JOptionPane.showMessageDialog(null, "La Categoria no se encuentra registrada");
            }
        } catch (NumberFormatException e) {

        }
    }//GEN-LAST:event_jBBuscarCategoriaActionPerformed

    private void jBLimpiarCamposGestionProductosActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jBLimpiarCamposGestionProductosActionPerformed
        // TODO add your handling code here:
        limpiarCamposRegistroProducto();
    }//GEN-LAST:event_jBLimpiarCamposGestionProductosActionPerformed

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        // TODO add your handling code here:
        limpiarCamposRegistroCategoria();
    }//GEN-LAST:event_jButton1ActionPerformed

    public void limpiarCamposRegistroCategoria() {
        jTFNombreCategoria.setText(null);
        jTFDescripcionCategoria.setText(null);
        codigoCategoria = -1;
    }

    public void limpiarCamposRegistroProducto() {
        jTFNombreProducto.setText(null);
        jTFDescripcionCate.setText(null);
        jCBCategorias.setSelectedIndex(0);
        jTADescripcionProducto.setText(null);
        codigoProducto = -1;
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jBBuscarCategoria;
    private javax.swing.JButton jBBuscarProducto;
    private javax.swing.JButton jBEditarCategoria;
    private javax.swing.JButton jBEditarProducto;
    private javax.swing.JButton jBEliminarCategoria;
    private javax.swing.JButton jBEliminarProducto;
    private javax.swing.JButton jBLimpiarCamposGestionProductos;
    private javax.swing.JButton jBRegistrarCategoria;
    private javax.swing.JButton jBRegistrarProducto;
    private javax.swing.JButton jButton1;
    private javax.swing.JComboBox jCBCategorias;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JPanel jPanel5;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JScrollPane jScrollPane3;
    private javax.swing.JScrollPane jScrollPane4;
    private javax.swing.JScrollPane jScrollPane5;
    private javax.swing.JTextArea jTADescripcionProducto;
    private javax.swing.JTable jTCategorias;
    private javax.swing.JTextArea jTFDescripcionCate;
    private javax.swing.JTextArea jTFDescripcionCategoria;
    private javax.swing.JTextField jTFNombreCategoria;
    private javax.swing.JTextField jTFNombreProducto;
    private javax.swing.JTable jTProductos;
    private javax.swing.JTabbedPane jTabbedPane1;
    private javax.swing.JTabbedPane jTabbedPane2;
    private javax.swing.JTabbedPane jTabbedPane3;
    // End of variables declaration//GEN-END:variables
}
