/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package Vista;

import Controlador.CtlEmpresario;
import Controlador.CtlProveedor;
import Controlador.CtlVentana;
import Modelo.Municipios;
import java.awt.Color;
import javax.swing.JOptionPane;

/**
 *
 * @author ASUS
 */
public class VentanaRegistro extends javax.swing.JFrame {

    /**
     * Creates new form VentanaRegProv
     */
    CtlEmpresario empresario;
    CtlProveedor proveedor;
    CtlVentana ventana;
    String tipoUsuario;

    public VentanaRegistro() {
        initComponents();
        this.setTitle("Subasta Inversa De Productos");
        this.getContentPane().setBackground(Color.WHITE);// Color de fondo de la ventana
        setLocationRelativeTo(this);
        empresario = new CtlEmpresario();
        proveedor = new CtlProveedor();
        ventana = new CtlVentana();
        String[] usuarios = {"Empresario", "Proveedor",};
        tipoUsuario = (String) JOptionPane.showInputDialog(this, "Con cual tipo de usuario deseas registrate?", "Tipo de Usuario", JOptionPane.INFORMATION_MESSAGE, null, usuarios, usuarios[0]);
        ventana.cargarDeptos(jCBDepto);

    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jTFNomCompleto = new javax.swing.JTextField();
        jTFCedula = new javax.swing.JTextField();
        jTFNick = new javax.swing.JTextField();
        jBRegistrarPro = new javax.swing.JButton();
        jLabel3 = new javax.swing.JLabel();
        jTFDireccion = new javax.swing.JTextField();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jTFNomEntidad = new javax.swing.JTextField();
        jLabel6 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        jLabel8 = new javax.swing.JLabel();
        jCBDepto = new javax.swing.JComboBox();
        jCBMunicipio = new javax.swing.JComboBox();
        jTFPass = new javax.swing.JTextField();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);

        jTFNomCompleto.setFont(new java.awt.Font("Century Gothic", 1, 12)); // NOI18N

        jTFCedula.setFont(new java.awt.Font("Century Gothic", 1, 12)); // NOI18N

        jTFNick.setFont(new java.awt.Font("Century Gothic", 1, 12)); // NOI18N

        jBRegistrarPro.setFont(new java.awt.Font("Century Gothic", 1, 12)); // NOI18N
        jBRegistrarPro.setText("Registrarse");
        jBRegistrarPro.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jBRegistrarProActionPerformed(evt);
            }
        });

        jLabel3.setFont(new java.awt.Font("Century Gothic", 1, 12)); // NOI18N
        jLabel3.setText("Nombre Completo:");

        jTFDireccion.setFont(new java.awt.Font("Century Gothic", 1, 12)); // NOI18N

        jLabel1.setFont(new java.awt.Font("Century Gothic", 1, 12)); // NOI18N
        jLabel1.setText("Cedula:");

        jLabel2.setFont(new java.awt.Font("Century Gothic", 1, 12)); // NOI18N
        jLabel2.setText("Nickname:");

        jLabel4.setFont(new java.awt.Font("Century Gothic", 1, 12)); // NOI18N
        jLabel4.setText("Password:");

        jLabel5.setFont(new java.awt.Font("Century Gothic", 1, 12)); // NOI18N
        jLabel5.setText("Direccion:");

        jTFNomEntidad.setFont(new java.awt.Font("Century Gothic", 1, 12)); // NOI18N

        jLabel6.setFont(new java.awt.Font("Century Gothic", 1, 12)); // NOI18N
        jLabel6.setText("Nombre Entidad:");

        jLabel7.setFont(new java.awt.Font("Century Gothic", 1, 12)); // NOI18N
        jLabel7.setText("Departamento:");

        jLabel8.setFont(new java.awt.Font("Century Gothic", 1, 12)); // NOI18N
        jLabel8.setText("Municipio:");

        jCBDepto.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "Seleccione una opcion", "1. Amazonas", "2. Antioquia", "3. Arauca", "4. Atlántico", "5. Bolívar", "6. Boyacá", "7. Caldas", "8. Caquetá", "9. Casanare", "10. Cauca", "11. Cesar", "12. Chocó", "13. Córdoba", "14. Cundinamarca", "15. Guainía", "16. Guaviare", "17. Huila", "18. La Guajira", "19. Magdalena", "20. Meta", "21. Nariño", "22. Norte de Santander", "23. Putumayo", "24. Quindio", "25. Risaralda", "26. San Andres y Providencia", "27. Santander", "28. Sucre", "29. Tolima", "30. Valle del Cauca", "31. Vaupés", "32. Vichada" }));
        jCBDepto.addItemListener(new java.awt.event.ItemListener() {
            public void itemStateChanged(java.awt.event.ItemEvent evt) {
                jCBDeptoItemStateChanged(evt);
            }
        });

        jCBMunicipio.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "Seleccione una opcion" }));

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(jLabel3)
                            .addComponent(jLabel1)
                            .addComponent(jLabel7)
                            .addComponent(jLabel8))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jTFCedula)
                            .addComponent(jCBDepto, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(jTFNomCompleto, javax.swing.GroupLayout.PREFERRED_SIZE, 230, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(0, 0, Short.MAX_VALUE))
                            .addComponent(jCBMunicipio, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addGap(0, 0, Short.MAX_VALUE)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                                .addComponent(jLabel2)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(jTFNick, javax.swing.GroupLayout.PREFERRED_SIZE, 230, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                                .addComponent(jLabel5)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(jTFDireccion, javax.swing.GroupLayout.PREFERRED_SIZE, 230, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                                .addComponent(jLabel6)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(jTFNomEntidad, javax.swing.GroupLayout.PREFERRED_SIZE, 230, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                                .addComponent(jLabel4)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addGroup(layout.createSequentialGroup()
                                        .addGap(10, 10, 10)
                                        .addComponent(jBRegistrarPro))
                                    .addComponent(jTFPass, javax.swing.GroupLayout.PREFERRED_SIZE, 230, javax.swing.GroupLayout.PREFERRED_SIZE))))))
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(24, 24, 24)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel3)
                    .addComponent(jTFNomCompleto, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel1)
                    .addComponent(jTFCedula, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel7)
                    .addComponent(jCBDepto, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel8)
                    .addComponent(jCBMunicipio, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jTFDireccion, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel5))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jTFNomEntidad, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel6))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jTFNick, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel2))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel4)
                    .addComponent(jTFPass, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jBRegistrarPro)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jBRegistrarProActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jBRegistrarProActionPerformed
        // TODO add your handling code here:
        if (ventana.verificarDatosGuardar(jTFNomCompleto, jTFCedula, jCBDepto,
                jTFDireccion, jTFNomEntidad, jTFNick, jTFPass)) {
            JOptionPane.showMessageDialog(null, "Digita todos los campos para registrar");
        } else {
            String nomCompleto = jTFNomCompleto.getText();
            String cedula = jTFCedula.getText();
            String mun = (String) jCBMunicipio.getSelectedItem();
            Municipios municipio = ventana.getGestionmun().searchMunNombre(mun);
            String direccion = jTFDireccion.getText();
            String nomEntidad = jTFNomEntidad.getText();
            String nick = jTFNick.getText();
            String pass = jTFPass.getText();
            if (tipoUsuario.equalsIgnoreCase("Proveedor")) {
                if (proveedor.save(cedula, nomCompleto, nick, pass, direccion, nomEntidad, municipio.getId())) {
                    JOptionPane.showMessageDialog(null, "El Proveedor ha quedado registrado");
                    limpiarCamposRegistroUsuario();
                } else {
                    JOptionPane.showMessageDialog(null, "El Proveedor ya se encuentra registrado");
                }
            } else if (empresario.save(cedula, nomCompleto, nick, pass, direccion, nomEntidad, municipio.getId())) {
                JOptionPane.showMessageDialog(null, "El Empresario ha quedado registrado");
                limpiarCamposRegistroUsuario();
            } else {
                JOptionPane.showMessageDialog(null, "El Empresario ya se encuentra registrado");
            }
        }
    }//GEN-LAST:event_jBRegistrarProActionPerformed

    private void jCBDeptoItemStateChanged(java.awt.event.ItemEvent evt) {//GEN-FIRST:event_jCBDeptoItemStateChanged
        // TODO add your handling code here:
        try {
            if (jCBDepto.getSelectedIndex() == 0) {
                jCBMunicipio.removeAllItems();
            } else {
                String depto = (String) jCBDepto.getSelectedItem();
                ventana.cargarMunicipios(depto, jCBMunicipio);
            }
        } catch (NullPointerException | NumberFormatException e) {
        }
    }//GEN-LAST:event_jCBDeptoItemStateChanged

    public void limpiarCamposRegistroUsuario() {
        jTFNomCompleto.setText(null);
        jTFCedula.setText(null);
        jCBDepto.setSelectedIndex(0);
        jTFDireccion.setText(null);
        jTFNomEntidad.setText(null);
        jTFNick.setText(null);
        jTFPass.setText(null);
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jBRegistrarPro;
    private javax.swing.JComboBox jCBDepto;
    private javax.swing.JComboBox jCBMunicipio;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JTextField jTFCedula;
    private javax.swing.JTextField jTFDireccion;
    private javax.swing.JTextField jTFNick;
    private javax.swing.JTextField jTFNomCompleto;
    private javax.swing.JTextField jTFNomEntidad;
    private javax.swing.JTextField jTFPass;
    // End of variables declaration//GEN-END:variables
}
